// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! The nv-telemetry schema compiler.
//!
//! Turns the annotated schema and its projection manifests into Rust. It is a
//! build-time tool: because generated code is checked in, nothing that
//! consumes the data plane depends on this crate.
//!
//! Generated output is deterministic, so a codegen change is reviewable as a
//! schema-shaped diff, and unchanged output is not rewritten. An annotation
//! the compiler cannot honor is an error rather than a warning; it never emits
//! silently degraded code.

use std::collections::BTreeSet;
use std::fmt;
use std::fs;
use std::io;
use std::path::Path;
use std::path::PathBuf;

use prost_reflect::DescriptorPool;

pub mod lint;
pub mod lock;
pub mod options;
pub mod projection;
pub mod provenance;
pub mod wire;
pub mod wrapper;

/// The observation contract. Only this package and its sub-packages are
/// subject to the invariant rules: the annotation and manifest packages
/// describe configuration, where a zero value cannot be mistaken for an
/// observation that was never made.
pub const CONTRACT_PACKAGE: &str = "nv.telemetry.v1";

/// Path of the checked-in contract lock, relative to the workspace root.
const LOCK_PATH: &str = "schema/contract.lock";

/// Path of the generated wire types, relative to the workspace root.
const WIRE_PATH: &str = "model/src/generated/wire.rs";

/// Path of the generated limit constants, relative to the workspace root.
const LIMITS_PATH: &str = "model/src/generated/limits.rs";

/// Path of the generated validated model, relative to the workspace root.
const MODEL_PATH: &str = "model/src/generated/model.rs";

/// Path of the generated module root, relative to the workspace root.
const GENERATED_MOD_PATH: &str = "model/src/generated/mod.rs";

/// Marker identifying the workspace root, used to locate it from the working
/// directory.
const ROOT_MARKER: &str = "buf.yaml";

/// The generated module root. Written rather than hand-maintained so the whole
/// directory is generated output and the staleness gate covers all of it.
const GENERATED_MOD: &str = "\
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generated by `make codegen`. Do not edit by hand.

// `pub` within a module that is itself crate-internal: reachable to the
// validated wrappers, invisible outside the crate.
#![allow(unreachable_pub)]

// Formatted by the generator and byte-compared against it. rustfmt.toml
// excludes generated trees, but `ignore` is nightly-only: stable rustfmt
// warns and reformats anyway, so a plain `cargo fmt` would rewrite the file
// and the staleness gate would then report a schema problem that does not
// exist. This attribute does not depend on a config file being honoured.
#[rustfmt::skip]
pub mod limits;

#[rustfmt::skip]
pub mod model;

#[rustfmt::skip]
pub mod wire;
";

/// Whether `package` is part of the observation contract.
///
/// Matched as a prefix rather than for equality, so that a future
/// `nv.telemetry.v1.gpu` is covered rather than silently unchecked.
#[must_use]
pub fn is_contract_package(package: &str) -> bool {
    package_within(package, CONTRACT_PACKAGE)
}

/// Whether `package` is `root` itself or a sub-package of it — and not a
/// sibling that merely shares the spelling, which is what the dot demands.
pub(crate) fn package_within(package: &str, root: &str) -> bool {
    package
        .strip_prefix(root)
        .is_some_and(|rest| rest.is_empty() || rest.starts_with('.'))
}

/// What the compiler was asked to do.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    /// Rewrite the generated trees.
    Generate,
    /// Report whether the generated trees are up to date, changing nothing.
    Check,
}

/// What the compiler did.
#[derive(Clone, Debug, Default)]
#[non_exhaustive]
pub struct Outcome {
    /// Messages examined in the contract package.
    pub examined: usize,
    /// Files written, in `Generate` mode.
    pub written: Vec<PathBuf>,
    /// Files whose content on disk differs from what would be generated.
    pub stale: Vec<PathBuf>,
    /// Files under a generated directory that no manifest produces anymore.
    /// Never touched: the operator deletes them — and drops the crate's
    /// `mod generated;` if the last manifest went with them.
    pub orphans: Vec<PathBuf>,
}

/// Why compilation could not proceed.
#[derive(Debug)]
pub enum Error {
    /// The embedded descriptor set could not be decoded.
    Pool(prost_reflect::DescriptorError),
    /// An annotation the compiler reads is absent, misshapen, or was lost.
    Vocabulary(options::VocabularyError),
    /// The schema violates a rule the compiler enforces.
    Schema(Vec<lint::Violation>),
    /// A projection manifest could not be loaded.
    ManifestLoad(projection::ManifestError),
    /// The source schema index could not be built.
    Index(projection::IndexError),
    /// A projection manifest declares what the compiler cannot honor.
    Manifests(Vec<projection::Violation>),
    /// Wire types could not be rendered from the descriptors.
    Backend(String),
    /// The workspace root could not be located from the working directory.
    Root(PathBuf),
    /// A generated file could not be read, written, or removed. Carries
    /// whatever was already written, because a failure partway through leaves
    /// artifacts that disagree with each other and the operator has to know
    /// which.
    Io {
        /// The path that failed.
        path: PathBuf,
        /// Paths written before the failure.
        written: Vec<PathBuf>,
        /// What went wrong.
        error: io::Error,
    },
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Pool(error) => write!(f, "descriptor set could not be decoded: {error}"),
            Self::Vocabulary(error) => write!(f, "{error}"),
            Self::Schema(violations) => {
                writeln!(f, "schema rejected by {} rule(s):", violations.len())?;
                for violation in violations {
                    writeln!(f, "  {violation}")?;
                }
                Ok(())
            }
            Self::Backend(detail) => write!(f, "{detail}"),
            Self::ManifestLoad(error) => write!(f, "{error}"),
            Self::Index(error) => write!(f, "{error}"),
            Self::Manifests(violations) => {
                writeln!(f, "manifests rejected by {} rule(s):", violations.len())?;
                for violation in violations {
                    writeln!(f, "  {violation}")?;
                }
                Ok(())
            }
            Self::Root(from) => write!(
                f,
                "no workspace root above `{}`: expected an ancestor containing `{ROOT_MARKER}`. \
                 Run this from inside the repository.",
                from.display()
            ),
            Self::Io {
                path,
                written,
                error,
            } => {
                write!(f, "{}: {error}", path.display())?;
                if !written.is_empty() {
                    write!(f, "\n  already written, now inconsistent with the rest:")?;
                    for written in written {
                        write!(f, "\n    {}", written.display())?;
                    }
                }
                Ok(())
            }
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Pool(error) => Some(error),
            Self::Vocabulary(error) => Some(error),
            Self::Io { error, .. } => Some(error),
            Self::ManifestLoad(error) => Some(error),
            Self::Index(error) => Some(error),
            Self::Schema(_) | Self::Backend(_) | Self::Root(_) | Self::Manifests(_) => None,
        }
    }
}

/// Decodes the schema shipped by `nv-telemetry-schema`.
///
/// # Errors
///
/// Returns [`Error::Pool`] if the embedded descriptor set is not a valid
/// `FileDescriptorSet`.
pub fn pool() -> Result<DescriptorPool, Error> {
    DescriptorPool::decode(nv_telemetry_schema::DESCRIPTOR_SET).map_err(Error::Pool)
}

/// Finds the workspace root by walking up from the working directory.
///
/// Deliberately not `CARGO_MANIFEST_DIR`: that is baked in at compile time,
/// and cargo does not rebuild this binary just because it is invoked from a
/// different checkout. With one `CARGO_TARGET_DIR` shared across two working
/// trees — a normal setup — a compile-time path makes `--check` validate the
/// tree the binary was built in while reporting on the one the operator is
/// standing in, and `generate` write into it. A gate that silently checks the
/// wrong repository is worse than no gate.
///
/// # Errors
///
/// Returns [`Error::Root`] if no ancestor of the working directory contains
/// the marker.
pub fn workspace_root() -> Result<PathBuf, Error> {
    let start = std::env::current_dir().map_err(|error| Error::Io {
        path: PathBuf::from("."),
        written: Vec::new(),
        error,
    })?;

    let mut candidate = start.as_path();
    loop {
        if candidate.join(ROOT_MARKER).is_file() {
            return Ok(candidate.to_path_buf());
        }
        candidate = candidate
            .parent()
            .ok_or_else(|| Error::Root(start.clone()))?;
    }
}

/// Runs the compiler over the shipped schema and reconciles generated output.
///
/// # Errors
///
/// Returns [`Error::Pool`] if the schema cannot be decoded,
/// [`Error::Vocabulary`] if the annotations are not as the compiler reads
/// them, [`Error::Schema`] if the schema breaks an invariant rule,
/// [`Error::Backend`] if wire types cannot be rendered, [`Error::Root`] if the
/// workspace root cannot be located, or [`Error::Io`] if a generated file
/// cannot be read or written.
pub fn run(mode: Mode) -> Result<Outcome, Error> {
    let pool = pool()?;
    let vocabulary = options::Vocabulary::resolve(&pool).map_err(Error::Vocabulary)?;

    let violations = lint::presence(&pool, &vocabulary);
    if !violations.is_empty() {
        return Err(Error::Schema(violations));
    }

    let examined = pool
        .all_messages()
        .filter(|message| is_contract_package(message.package_name()) && !message.is_map_entry())
        .count();

    let here = workspace_root()?;
    let here = here.as_path();

    let mut artifacts = vec![
        (
            here.join(LOCK_PATH),
            lock::Snapshot::capture(&pool, &vocabulary).render(),
        ),
        (
            here.join(WIRE_PATH),
            wire::generate(&pool).map_err(Error::Backend)?,
        ),
        (here.join(LIMITS_PATH), wrapper::limits(&pool, &vocabulary)),
        (
            here.join(MODEL_PATH),
            wrapper::model(&pool, &vocabulary).map_err(Error::Backend)?,
        ),
        (here.join(GENERATED_MOD_PATH), GENERATED_MOD.to_owned()),
    ];

    // The CSDL bundle is parsed only when a manifest exists to compile.
    let manifests = projection::load(here, &pool).map_err(Error::ManifestLoad)?;
    if !manifests.is_empty() {
        let bundle = projection::Bundle::dmtf().map_err(Error::Index)?;
        let index = bundle.index().map_err(Error::Index)?;
        let checked = projection::compile(&manifests, &index, &pool, &vocabulary)
            .map_err(Error::Manifests)?;
        let generated =
            projection::emit(&checked, &index, &pool, &vocabulary).map_err(Error::Backend)?;
        for (path, rendered) in generated {
            artifacts.push((here.join(path), rendered));
        }
    }

    // Artifact paths are distinct by construction: the fixed outputs live
    // under `model/` and `schema/`, and per-crate module collisions are
    // already manifest violations.
    let artifact_paths: BTreeSet<PathBuf> =
        artifacts.iter().map(|(path, _)| path.clone()).collect();

    let mut outcome = Outcome {
        examined,
        written: Vec::new(),
        stale: Vec::new(),
        orphans: Vec::new(),
    };

    for (path, rendered) in artifacts {
        let committed = match fs::read_to_string(&path) {
            Ok(text) => Some(text),
            Err(error) if error.kind() == io::ErrorKind::NotFound => None,
            Err(error) => {
                return Err(Error::Io {
                    path,
                    written: outcome.written,
                    error,
                })
            }
        };

        if committed.as_deref() == Some(rendered.as_str()) {
            continue;
        }

        match mode {
            Mode::Check => outcome.stale.push(path),
            Mode::Generate => {
                if let Some(parent) = path.parent() {
                    if let Err(error) = fs::create_dir_all(parent) {
                        return Err(Error::Io {
                            path: parent.to_path_buf(),
                            written: outcome.written,
                            error,
                        });
                    }
                }
                if let Err(error) = fs::write(&path, &rendered) {
                    return Err(Error::Io {
                        path,
                        written: outcome.written,
                        error,
                    });
                }
                outcome.written.push(path);
            }
        }
    }

    outcome.orphans =
        generated_orphans(here, &artifact_paths).map_err(|(path, error)| Error::Io {
            path,
            written: outcome.written.clone(),
            error,
        })?;

    Ok(outcome)
}

/// Files under `sources/*/src/generated/` that the compiler no longer
/// produces — a deleted manifest's module would otherwise sit outside the
/// staleness gate forever. Detection only; nothing is removed.
fn generated_orphans(
    root: &Path,
    expected: &BTreeSet<PathBuf>,
) -> Result<Vec<PathBuf>, (PathBuf, io::Error)> {
    let sources = root.join("sources");
    let crates = match fs::read_dir(&sources) {
        Ok(entries) => entries,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err((sources, error)),
    };

    let mut orphans = Vec::new();
    for entry in crates {
        let entry = entry.map_err(|error| (sources.clone(), error))?;
        let generated = entry.path().join("src").join("generated");
        let files = match fs::read_dir(&generated) {
            Ok(files) => files,
            Err(error) if error.kind() == io::ErrorKind::NotFound => continue,
            Err(error) => return Err((generated, error)),
        };
        for file in files {
            let file = file.map_err(|error| (generated.clone(), error))?;
            let path = file.path();
            if !expected.contains(&path) {
                orphans.push(path);
            }
        }
    }
    orphans.sort();
    Ok(orphans)
}
