// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! The contract lock: a checked-in, deterministic record of every declaration
//! in the contract package.
//!
//! Regenerating it and finding the working tree unchanged is what makes
//! `--check` able to fail, so a schema edit without a regenerated tree cannot
//! reach CI. It stands in for the generated Rust until there is any, and
//! remains useful afterwards as a readable record of the contract.
//!
//! The lock records current declarations, including enum values and oneofs,
//! so edits surface as diffs. It checks freshness, not compatibility with
//! historical revisions; the contract is still under development.
//!
//! One deliberate blindness: with `allow_alias`, values come back sorted by
//! number, so swapping which alias is declared first — observable in JSON and
//! text format — does not diff the lock. The contract declares no aliases.
//!
//! The format is one sorted line per declaration so that a review reads it as
//! a schema-shaped diff. Staleness is a byte comparison against the committed
//! file, so nothing reads it back: a change to the header is as much a reason
//! to regenerate as a change to a field.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write as _;

use prost_reflect::DescriptorPool;
use prost_reflect::FieldDescriptor;
use prost_reflect::Kind;

use crate::is_contract_package;
use crate::options::FieldInvariant;
use crate::options::MessageInvariant;
use crate::options::Vocabulary;
use crate::options::FIELD_OPTIONS;
use crate::options::MESSAGE_OPTIONS;

const HEADER: &str = "\
# nv-telemetry contract lock.
#
# Generated by `make codegen`; do not edit. One line per declaration, sorted,
# so that a schema change reads as a diff. `make check-codegen` fails if this
# file disagrees with the schema. This is a snapshot of the current contract,
# not a compatibility baseline for historical revisions.
";

/// One field as the lock records it.
///
/// Annotations are recorded alongside the shape because they are what decides
/// whether a zero can be fabricated. A lock that tracked only numbers and
/// types would let `finite` or `zero_is_meaningful` be added or removed with
/// no diff at all, which is most of what the lock is for.
#[derive(Clone, Debug, PartialEq, Eq)]
struct Entry {
    name: String,
    kind: String,
    cardinality: String,
    presence: String,
    annotations: String,
}

/// Every declaration in the contract, keyed by message and field number.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Snapshot {
    fields: BTreeMap<(String, u32), Entry>,
    messages: BTreeSet<String>,
    // Enum values and oneofs are recorded because the semantics live there as
    // much as in the fields. Without them, adding a failure class or deleting
    // the `required` from a oneof — which is what keeps an empty Value
    // distinguishable from an explicit null — leaves the lock unchanged.
    enums: BTreeSet<String>,
    oneofs: BTreeSet<String>,
}

impl Snapshot {
    /// Records every contract declaration in `pool`.
    pub fn capture(pool: &DescriptorPool, vocabulary: &Vocabulary) -> Self {
        let mut snapshot = Self::default();

        for message in pool.all_messages() {
            if !is_contract_package(message.package_name()) || message.is_map_entry() {
                continue;
            }
            let annotations = vocabulary
                .message_invariant(&message)
                .map_or_else(String::new, render_message_invariant);
            snapshot.messages.insert(
                format!("{} {annotations}", message.full_name())
                    .trim_end()
                    .to_owned(),
            );

            for oneof in message.oneofs() {
                // proto3 `optional` compiles to a synthetic one-field oneof.
                // Recording those would restate presence, which the field
                // lines already carry.
                if oneof.is_synthetic() {
                    continue;
                }
                let required = vocabulary
                    .oneof_invariant(&oneof)
                    .is_some_and(|invariant| invariant.required);
                let mut numbers: Vec<u32> = oneof.fields().map(|field| field.number()).collect();
                numbers.sort_unstable();
                let members: Vec<String> = numbers
                    .into_iter()
                    .map(|number| number.to_string())
                    .collect();
                snapshot.oneofs.insert(format!(
                    "{} [{}]{}",
                    oneof.full_name(),
                    members.join(","),
                    if required { " required" } else { "" }
                ));
            }

            for field in message.fields() {
                snapshot.fields.insert(
                    (message.full_name().to_owned(), field.number()),
                    Entry {
                        name: field.name().to_owned(),
                        kind: kind_name(&field),
                        annotations: field_annotations(vocabulary, &field),
                        cardinality: if field.is_map() {
                            "map"
                        } else if field.is_list() {
                            "repeated"
                        } else {
                            "single"
                        }
                        .to_owned(),
                        presence: if field.supports_presence() {
                            "explicit"
                        } else {
                            "implicit"
                        }
                        .to_owned(),
                    },
                );
            }
        }

        for enumeration in pool.all_enums() {
            if !is_contract_package(enumeration.package_name()) {
                continue;
            }
            let values: Vec<String> = enumeration
                .values()
                .map(|value| format!("{}={}", value.name(), value.number()))
                .collect();
            snapshot
                .enums
                .insert(format!("{} {}", enumeration.full_name(), values.join(" ")));
        }

        snapshot
    }

    /// Renders the lock file.
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        for name in &self.messages {
            let _ = writeln!(out, "message {name}");
        }
        for name in &self.enums {
            let _ = writeln!(out, "enum {name}");
        }
        for name in &self.oneofs {
            let _ = writeln!(out, "oneof {name}");
        }
        for ((message, number), entry) in &self.fields {
            let _ = writeln!(
                out,
                "{}",
                format!(
                    "field {message} {number} {} {} {} {} {}",
                    entry.name, entry.kind, entry.cardinality, entry.presence, entry.annotations
                )
                .trim_end()
            );
        }
        out
    }
}

/// Renders a field's type.
///
/// A map is rendered as its key and value types rather than as the synthetic
/// entry message, whose name is derived from the field name and so hides both.
/// Changing a map's key type from `string` to `int64` is wire-breaking and
/// would otherwise leave the lock unchanged.
fn kind_name(field: &FieldDescriptor) -> String {
    if field.is_map() {
        if let Kind::Message(entry) = field.kind() {
            return format!(
                "map<{},{}>",
                type_name(&entry.map_entry_key_field().kind()),
                type_name(&entry.map_entry_value_field().kind())
            );
        }
    }
    type_name(&field.kind())
}

fn type_name(kind: &Kind) -> String {
    match kind {
        Kind::Message(message) => message.full_name().to_owned(),
        Kind::Enum(enumeration) => enumeration.full_name().to_owned(),
        other => format!("{other:?}").to_lowercase(),
    }
}

fn field_annotations(vocabulary: &Vocabulary, field: &FieldDescriptor) -> String {
    let Some(invariant) = vocabulary.field_invariant(field) else {
        return String::new();
    };
    render_field_invariant(&invariant)
}

/// Renders a message's annotations, one part per option-table row.
fn render_message_invariant(invariant: MessageInvariant) -> String {
    let parts: Vec<String> = MESSAGE_OPTIONS
        .iter()
        .filter_map(|option| (option.render)(invariant))
        .collect();
    parts.join(" ")
}

/// Renders one field's annotations, one part per option-table row.
///
/// The rendering is a column of the table, so an option cannot exist without a
/// lock line — which matters more here than at any other consumer: the lock is
/// the only gate that sees an annotation's value at all, and the hand-kept
/// list this replaces needed a coverage test to keep options from quietly
/// going unrecorded.
fn render_field_invariant(invariant: &FieldInvariant) -> String {
    let parts: Vec<String> = FIELD_OPTIONS
        .iter()
        .filter_map(|option| (option.render)(invariant))
        .collect();
    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::render_field_invariant;
    use super::render_message_invariant;
    use crate::options::FieldInvariant;
    use crate::options::MessageInvariant;
    use crate::options::Vocabulary;

    /// A `FieldInvariant` with every option carrying a non-default value.
    ///
    /// Written out in full rather than derived, because the point is that it
    /// stops compiling when the vocabulary gains a field. A `..Default`
    /// shorthand would leave the new field at its default, and the assertion
    /// below would then report a missing lock line for something the author
    /// had not been told to think about.
    fn everything_set() -> FieldInvariant {
        FieldInvariant {
            zero_is_meaningful: true,
            finite: true,
            required: true,
            unordered: true,
            max_items: Some(1),
            max_len: Some(1),
            collection_metadata: true,
            non_empty: true,
            reject_unspecified: true,
            unique_by: vec!["k".to_owned()],
        }
    }

    /// The message-level counterpart, written out in full for the same reason.
    fn every_message_option_set() -> MessageInvariant {
        MessageInvariant {
            validated: true,
            hashable: true,
            max_depth: Some(1),
        }
    }

    #[test]
    fn every_option_the_compiler_reads_reaches_the_lock() {
        // Every annotation value must appear in the lock's review surface. The renderer iterates the option table, which makes a
        // *forgotten* line impossible; what this still guards is a *wrong*
        // one — a row whose render returns `None` when set, or renders a
        // string that fails to name the option.
        //
        // All three option kinds, because the argument does not care which
        // declaration an option hangs off, and covering only fields would
        // leave `hashable` free to vanish from the lock unnoticed.
        let fields = render_field_invariant(&everything_set());
        for option in Vocabulary::field_option_names() {
            assert!(
                fields.contains(option),
                "field option `{option}` is read by the compiler but never \
                 reaches the contract lock, so changing it on a field would \
                 produce no diff; rendered as `{fields}`"
            );
        }

        let messages = render_message_invariant(every_message_option_set());
        for option in Vocabulary::message_option_names() {
            assert!(
                messages.contains(option),
                "message option `{option}` is read by the compiler but never \
                 reaches the contract lock; rendered as `{messages}`"
            );
        }

        // A oneof carries one option, and the lock records it as a suffix on
        // the oneof line rather than as a named token — so there is no
        // rendering to drive, and the honest check is that the vocabulary
        // still has exactly the one option that suffix stands for. A second
        // one would otherwise be read by the compiler and recorded nowhere.
        assert_eq!(
            Vocabulary::oneof_option_names(),
            ["required"],
            "the oneof vocabulary grew; the lock records only `required`, as a \
             suffix on the oneof line, so give the new option a place in \
             `Snapshot::capture` and extend this"
        );
    }
}
