// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Provenance tables.
//!
//! Emits the mapping from each contract field to the source path it was
//! projected from, so tooling can answer where a reading came from. This is
//! the planner's explainability requirement extended to data.
//!
//! One row per source read a generated projection performs — the subject's
//! identity contributors, field mappings, and assembly entries, expansion
//! members substituted — in manifest order. A text emitter, like `limits`:
//! a flat table of constants earns no tokens.

use std::fmt::Write as _;

use crate::projection::spec::ManifestSpec;
use crate::projection::spec::ScopeSpec;

const PROVENANCE_HEADER: &str = "\
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generated by `make codegen` from the manifests under `manifests/`.
//! Do not edit.
//!
//! Which manifest declaration produced which extraction: one row per source
//! read a generated projection performs. Tooling that must answer where a
//! value came from reads this instead of the projection bodies.

// Emitted whether or not anything consumes it yet, exactly as the wire
// types are.
#![allow(dead_code)]

/// One generated extraction and the declaration it came from.
pub(crate) struct Extraction {
    /// The manifest file, workspace-relative.
    pub(crate) manifest: &'static str,
    /// The projection's name within it.
    pub(crate) projection: &'static str,
    /// The read that produced the value: a source-type-prefixed payload
    /// path, or the requested location's template capture.
    pub(crate) source: &'static str,
    /// Where the value landed: a contract field, an assembly entry as
    /// `field[\"key\"]`, or the derived subject's own parts.
    pub(crate) target: &'static str,
}
";

#[derive(Clone, Debug)]
pub(crate) struct Row {
    pub(crate) manifest: String,
    pub(crate) projection: String,
    pub(crate) source: String,
    pub(crate) target: String,
}

/// Lowers one crate's checked manifests into provenance rows.
#[must_use]
pub(crate) fn collect(manifests: &[&ManifestSpec]) -> Vec<Row> {
    let mut rows = Vec::new();
    for manifest in manifests {
        let relative = manifest.relative_path();
        for projection in &manifest.projections {
            // Identity is a source read too: without these rows the table
            // could not answer where the subject on every emitted message
            // came from.
            if let Some(subject) = projection.subject.as_ref().or(manifest.subject.as_ref()) {
                for (position, contributor) in subject.scope.iter().enumerate() {
                    let source = match contributor {
                        ScopeSpec::PayloadPath(path) => {
                            format!("{}.{path}", projection.source_type)
                        }
                        ScopeSpec::LocationTemplate { template, capture } => {
                            format!("location `{template}` capture `{capture}`")
                        }
                        ScopeSpec::PathKey(key) => format!("path key `{key}`"),
                        ScopeSpec::Unset => continue,
                    };
                    rows.push(Row {
                        manifest: relative.clone(),
                        projection: projection.name.clone(),
                        source,
                        target: format!("subject.scope[{position}]"),
                    });
                }
                rows.push(Row {
                    manifest: relative.clone(),
                    projection: projection.name.clone(),
                    source: format!("{}.{}", projection.source_type, subject.id_path),
                    target: "subject.id".to_owned(),
                });
            }
            // Provenance fields are compiler-filled, not declared; the table
            // still answers where the value came from.
            if let Some(provenance) =
                crate::projection::lint::target_profile(&projection.target_type)
                    .and_then(|profile| profile.provenance)
            {
                rows.push(Row {
                    manifest: relative.clone(),
                    projection: projection.name.clone(),
                    source: "requested location (canonical)".to_owned(),
                    target: format!("{}.{provenance}", projection.target_type),
                });
            }
            for instance in projection.instances() {
                for field in &instance.fields {
                    rows.push(Row {
                        manifest: relative.clone(),
                        projection: projection.name.clone(),
                        source: format!("{}.{}", projection.source_type, field.source_path),
                        target: format!("{}.{}", projection.target_type, field.target_field),
                    });
                }
                for assembly in &instance.map_assemblies {
                    for entry in &assembly.entries {
                        rows.push(Row {
                            manifest: relative.clone(),
                            projection: projection.name.clone(),
                            source: format!("{}.{}", projection.source_type, entry.source_path),
                            target: format!(
                                "{}.{}[{:?}]",
                                projection.target_type, assembly.target_field, entry.key
                            ),
                        });
                    }
                }
            }
        }
    }
    rows
}

/// Renders one crate's already-lowered provenance table.
#[must_use]
pub(crate) fn render(rows: &[Row]) -> String {
    let mut out = String::from(PROVENANCE_HEADER);
    out.push_str("\n/// Every extraction, in manifest order.\n");
    out.push_str("pub(crate) const PROVENANCE: &[Extraction] = &[\n");
    for row in rows {
        let Row {
            manifest,
            projection,
            source,
            target,
        } = row;
        let _ = write!(
            out,
            "    Extraction {{\n        manifest: {manifest:?},\n        \
             projection: {projection:?},\n        source: {source:?},\n        \
             target: {target:?},\n    }},\n"
        );
    }
    out.push_str("];\n");
    out
}
